// Copyright 2026 Metaversal Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Build the wasm executable (run from this crate's directory):
//    cargo build --target wasm32-unknown-unknown --release --target-dir target
// Output: target/wasm32-unknown-unknown/release/solar_system.wasm
// Always pass --target-dir target; otherwise a CARGO_TARGET_DIR set in the shell
// can redirect the output elsewhere.

#![allow(non_snake_case, non_camel_case_types, dead_code)]

// ---------------------------------------------------------------------------
// Solar System WASM module
//
// Builds the whole solar-system scene programmatically: a STARSYSTEM root frame
// (object index 2) with the Sun, planets, moons, and debris hung beneath it.
// Every body is submitted with an explicit object index, so a child names its
// parent directly by index (Submit_System / Submit_Body / Submit_Surface). The
// per-body data lives in the generated submodules; this file owns only the
// three submit helpers and the lifecycle.
//
// It talks to the engine entirely through the sneeze SDK - the single-Call
// ABI - importing only Sneeze.Call and exporting the lifecycle plus the
// Alloc/Free/Notify memory hooks (all generated by sneeze::instance!).
// ---------------------------------------------------------------------------

use sneeze::*;

mod star;
mod planets;
mod moons_earth;
mod moons_mars;
mod moons_jupiter;
mod moons_saturn;
mod moons_uranus;
mod moons_neptune;
mod moons_pluto;
mod debris;

// Object class (mirrors MAP_OBJECT_CLASS in include/Map_Object.h). Every node
// this module builds is CELESTIAL, so every parent reference is too.
const MAP_OBJECT_CLASS_CELESTIAL: u16 = 71;

// Celestial types (mirror MAP_OBJECT_TYPE_TYPE_CELESTIAL). The generated
// submodules pass these as raw numbers; the full table is kept here as the
// reference for what each value means. STARSYSTEM and SURFACE are used below.
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_NONE           : u8 = 0;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_UNIVERSE       : u8 = 1;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_SUPERCLUSTER   : u8 = 2;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_GALAXYCLUSTER  : u8 = 3;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_GALAXY         : u8 = 4;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_SECTOR         : u8 = 5;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_NEBULA         : u8 = 6;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_STARCLUSTER    : u8 = 7;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_BLACKHOLE      : u8 = 8;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_STARSYSTEM     : u8 = 9;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_STAR           : u8 = 10;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_PLANETSYSTEM   : u8 = 11;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_PLANET         : u8 = 12;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_MOONSYSTEM     : u8 = 125;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_MOON           : u8 = 13;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_DEBRISSYSTEM   : u8 = 135;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_DEBRIS         : u8 = 14;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_SATELLITE      : u8 = 15;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_TRANSPORT      : u8 = 16;
const MAP_OBJECT_TYPE_TYPE_CELESTIAL_SURFACE        : u8 = 17;

const TEX_BASE: &str = "https://cdn.rp1.com/res/texture/celestial/";

// The opened fabric index, stashed for the free-function Submit_* helpers the
// generated submodules call. Single-threaded wasm; written once at Open before
// any Submit_* runs, read-only thereafter.
static mut G_TWFABRICIX: u64 = 0;

fn Fabric () -> FABRIC
{
   FABRIC::New (unsafe { G_TWFABRICIX })
}

// ---------------------------------------------------------------------------
// Submit helpers - build and submit one map object per call. Three variants
// match the three levels of the scene hierarchy:
//   System  - orbital frame (STARSYSTEM, PLANETSYSTEM, MOONSYSTEM, DEBRISSYSTEM)
//   Body    - physical body (STAR, PLANET, MOON, DEBRIS)
//   Surface - texture attachment (SURFACE)
// Each names its own object index (nSelf) and its parent's (nParent).
// ---------------------------------------------------------------------------

#[allow(clippy::too_many_arguments)]
fn Submit_System (nParent: u64, nSelf: u64, sName: &str, bType: u8, dA: f64, dB: f64, tmPeriod: i64, tmOrigin: i64, qx: f64, qy: f64, qz: f64, qw: f64, precX: f64, precY: f64, precZ: f64, dBound: f64, fMass: f32, nColor: u32)
{
   let mut pObject = SNEEZE_ABI_MAPOBJECT::Celestial ();

   pObject.Parent               (MAP_OBJECT_CLASS_CELESTIAL, nParent)
          .ObjectIx             (nSelf)
          .Type                 (bType)
          .Name                 (sName)
          .Position             (precX, precY, precZ)
          .Rotation             (qx, qy, qz, qw)
          .Bound                (dBound, dBound, dBound)
          .Orbit                (dA, dB, tmPeriod, tmOrigin)
          .Properties_Celestial (fMass, 0.0, nColor, 0.0, 0.0);

   let _ = Fabric ().Scene ().Node_Open (&pObject);
}

#[allow(clippy::too_many_arguments)]
fn Submit_Body (nParent: u64, nSelf: u64, sName: &str, bType: u8, dRadius: f64, fMass: f32, nColor: u32, qx: f64, qy: f64, qz: f64, qw: f64, precX: f64, precY: f64, precZ: f64)
{
   let mut pObject = SNEEZE_ABI_MAPOBJECT::Celestial ();

   pObject.Parent               (MAP_OBJECT_CLASS_CELESTIAL, nParent)
          .ObjectIx             (nSelf)
          .Type                 (bType)
          .Name                 (sName)
          .Position             (precX, precY, precZ)
          .Rotation             (qx, qy, qz, qw)
          .Bound                (dRadius, dRadius, dRadius)
          .Properties_Celestial (fMass, 0.0, nColor, 0.0, 0.0);

   let _ = Fabric ().Scene ().Node_Open (&pObject);
}

fn Submit_Surface (nParent: u64, nSelf: u64, sName: &str, sTexture: &str, dW0Rad: f64, tmSpinPeriod: i64)
{
   let mut pObject = SNEEZE_ABI_MAPOBJECT::Celestial ();

   pObject.Parent   (MAP_OBJECT_CLASS_CELESTIAL, nParent)
          .ObjectIx (nSelf)
          .Type     (MAP_OBJECT_TYPE_TYPE_CELESTIAL_SURFACE)
          .Name     (sName)
          .Orbit    (dW0Rad, 0.0, tmSpinPeriod, 0);

   if !sTexture.is_empty ()
   {
      let sUrl = [TEX_BASE, sTexture].concat ();
      pObject.Reference (&sUrl);
   }

   let _ = Fabric ().Scene ().Node_Open (&pObject);
}

// ---------------------------------------------------------------------------
// WASM lifecycle
// ---------------------------------------------------------------------------

struct SOLAR_SYSTEM;

impl INSTANCE for SOLAR_SYSTEM
{
   fn Open (pFabric: FABRIC)
   {
      unsafe { G_TWFABRICIX = pFabric.Index (); }

      let pConsole = pFabric.Console ();

      pConsole.Log (&format! ("Solar System WASM: Open (twFabricIx={})", pFabric.Index ()));

      // The "Solar System" frame (object index 2, STARSYSTEM) is the fabric's
      // root node; every body below names index 2 as its ultimate parent.
      let mut pRoot = SNEEZE_ABI_MAPOBJECT::Celestial ();

      pRoot.ObjectIx             (2)
           .Type                 (MAP_OBJECT_TYPE_TYPE_CELESTIAL_STARSYSTEM)
           .Name                 ("Solar System")
           .Properties_Celestial (0.0, 0.0, 0x00888888, 0.0, 0.0);

      let pNode = pFabric.Scene ().Node_Root (&pRoot);

      if pNode.IsValid ()
      {
         let mut nTotal: u32 = 0;

         nTotal += star::Submit ();
         nTotal += planets::Submit ();
         nTotal += moons_earth::Submit ();
      // nTotal += moons_mars::Submit ();
      // nTotal += moons_jupiter::Submit ();
      // nTotal += moons_saturn::Submit ();
      // nTotal += moons_uranus::Submit ();
      // nTotal += moons_neptune::Submit ();
      // nTotal += moons_pluto::Submit ();
         nTotal += debris::Submit ();

         pConsole.Log (&format! ("  Solar system complete: {} objects", nTotal));
      }
      else
      {
         pConsole.Error ("  ERROR: Failed to create root node");
      }
   }

   fn Close (pFabric: FABRIC)
   {
      pFabric.Console ().Log ("Solar System WASM: Close");
   }
}

sneeze::instance! (SOLAR_SYSTEM);
