// Copyright 2026 Metaversal Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "Network.h"

// Sockets are the only part of the engine that needs Winsock. The PCH keeps
// windows.h lean (WIN32_LEAN_AND_MEAN) so that this is the include which
// establishes Winsock 2, ahead of asio, rather than windows.h quietly
// establishing Winsock 1 everywhere.
#ifdef _WIN32
#include <winsock2.h>
#include <ws2tcpip.h>
#endif

#include <websocketpp/config/asio_client.hpp>
#include <websocketpp/client.hpp>

namespace SNEEZE
{
   // The Mozilla CA bundle compiled into the library (generated by
   // src/CMakeLists.txt). The fetch path only needs it on platforms with no
   // trust store of their own; BoringSSL never has one, so every socket
   // verifies against this.
   extern const char*  const g_szCaCertPem;
   extern const unsigned long g_nCaCertPemLen;
}

using namespace SNEEZE;

typedef websocketpp::client<websocketpp::config::asio_tls_client> CLIENT_TLS;
typedef websocketpp::client<websocketpp::config::asio_client>     CLIENT_PLAIN;

// The protocol allows 123 bytes of close reason. Truncating blindly can split a
// UTF-8 sequence, which the transport then rejects and the close fails outright,
// so any trailing partial sequence goes with it.

static std::string Reason_Trim (const std::string& sReason)
{
   std::string sResult = sReason.substr (0, 123);

   while (!sResult.empty ()  &&  (static_cast<unsigned char> (sResult.back ()) & 0xC0) == 0x80)
      sResult.pop_back ();

   // What is left is either whole or ends on a lead byte with its continuation
   // bytes cut off, which is the one case the loop above cannot see.
   if (!sResult.empty ()  &&  (static_cast<unsigned char> (sResult.back ()) & 0xC0) == 0xC0)
      sResult.pop_back ();

   return sResult;
}

// The TLS context every wss:// connection gets. websocketpp sets SNI itself from
// the connection's URI; the host name check is ours to install.

static std::shared_ptr<asio::ssl::context> Tls_Context (CLIENT_TLS* pClient, websocketpp::connection_hdl hdl)
{
   std::shared_ptr<asio::ssl::context> pContext = std::make_shared<asio::ssl::context> (asio::ssl::context::tls_client);

   websocketpp::lib::error_code ec;

   pContext->set_options (asio::ssl::context::default_workarounds | asio::ssl::context::no_sslv2 | asio::ssl::context::no_sslv3, ec);
   pContext->set_verify_mode (asio::ssl::verify_peer, ec);
   pContext->add_certificate_authority (asio::const_buffer (g_szCaCertPem, g_nCaCertPemLen), ec);

   CLIENT_TLS::connection_ptr pConn = pClient->get_con_from_hdl (hdl, ec);

   if (pConn  &&  pConn->get_uri ())
      pContext->set_verify_callback (asio::ssl::host_name_verification (pConn->get_uri ()->get_host ()), ec);

   return pContext;
}

/***********************************************************************************************************************************
**  ISOCKET_LINK
***********************************************************************************************************************************/

ISOCKET_LINK::ISOCKET_LINK ()  {}
ISOCKET_LINK::~ISOCKET_LINK () {}

/***********************************************************************************************************************************
**  SOCKET_HUB Impl Class
***********************************************************************************************************************************/

class SOCKET_HUB::Impl
{
public:

   // One live connection.
   //
   // Held through a shared_ptr because two threads reach it from opposite ends:
   // the caller's, which finds it in the table, and the io thread's, whose
   // handlers captured a weak reference to it. The weak reference is what keeps
   // the connection from owning the entry that owns the connection.
   //
   // mxEntry is held across every callback into pLink AND taken by Detach, which
   // is the whole mechanism behind Detach's promise that no callback is running
   // when it returns.

   struct ENTRY
   {
      ISOCKET_LINK*                                   pLink       { nullptr };
      CLIENT_TLS::connection_ptr                      pConn_Tls;
      CLIENT_PLAIN::connection_ptr                    pConn_Plain;
      std::mutex                                      mxEntry;
      bool                                            bDetached   { false };
   };

   typedef std::shared_ptr<ENTRY> ENTRY_PTR;

   Impl () :
      m_bRunning (false)
   {
   }

   ~Impl ()
   {
      Shutdown ();
   }

   bool Initialize ()
   {
      bool bResult = false;

      // websocketpp logs to stdout by default, which is not where any of the
      // engine's diagnostics go.
      m_ClientTls.clear_access_channels (websocketpp::log::alevel::all);
      m_ClientTls.clear_error_channels  (websocketpp::log::elevel::all);
      m_ClientTls.init_asio (&m_ioContext);
      m_ClientTls.set_max_message_size (kSOCKET_FRAME_MAX);
      m_ClientTls.set_tls_init_handler ([this] (websocketpp::connection_hdl hdl) { return Tls_Context (&m_ClientTls, hdl); });

      m_ClientPlain.clear_access_channels (websocketpp::log::alevel::all);
      m_ClientPlain.clear_error_channels  (websocketpp::log::elevel::all);
      m_ClientPlain.init_asio (&m_ioContext);
      m_ClientPlain.set_max_message_size (kSOCKET_FRAME_MAX);

      // The work guard is what keeps run() from returning the moment the last
      // connection goes idle. Shutdown releases it.
      m_pWork = std::make_unique<asio::executor_work_guard<asio::io_context::executor_type>> (asio::make_work_guard (m_ioContext));

      // A plain std::thread rather than a THREAD: asio owns the loop, so there
      // is no Tick to write and nothing for the metronome to wake.
      m_thIo = std::thread ([this] { m_ioContext.run (); });

      m_bRunning = true;

      bResult = true;

      return bResult;
   }

   void Shutdown ()
   {
      if (m_bRunning)
      {
         m_bRunning = false;

         // Anything still connected loses its link first, so no handler can
         // reach a SOCKET while the loop is winding down.
         std::vector<ENTRY_PTR> apEntry;

         {
            std::lock_guard<std::mutex> guard (m_mxHub);

            apEntry = m_apEntry;

            m_apEntry.clear ();
         }

         for (auto& pEntry : apEntry)
         {
            std::lock_guard<std::mutex> guard (pEntry->mxEntry);

            pEntry->bDetached = true;
         }

         apEntry.clear ();

         m_pWork.reset ();

         m_ioContext.stop ();

         if (m_thIo.joinable ())
            m_thIo.join ();
      }
   }

   bool Connect (ISOCKET_LINK* pLink, const std::string& sUrl, const std::string& sProtocol)
   {
      bool bResult = false;

      bool bTls   = (sUrl.compare (0, 6, "wss://") == 0);
      bool bPlain = (sUrl.compare (0, 5, "ws://")  == 0);

      if (m_bRunning  &&  pLink  &&  (bTls  ||  bPlain))
      {
         ENTRY_PTR pEntry = std::make_shared<ENTRY> ();

         pEntry->pLink = pLink;

         websocketpp::lib::error_code ec;

         if (bTls)
         {
            pEntry->pConn_Tls = m_ClientTls.get_connection (sUrl, ec);

            if (!ec  &&  pEntry->pConn_Tls)
            {
               Subprotocol_Add (pEntry->pConn_Tls, sProtocol);
               Handler_Set     (&m_ClientTls, pEntry->pConn_Tls, std::weak_ptr<ENTRY> (pEntry));

               bResult = true;
            }
         }
         else
         {
            pEntry->pConn_Plain = m_ClientPlain.get_connection (sUrl, ec);

            if (!ec  &&  pEntry->pConn_Plain)
            {
               Subprotocol_Add (pEntry->pConn_Plain, sProtocol);
               Handler_Set     (&m_ClientPlain, pEntry->pConn_Plain, std::weak_ptr<ENTRY> (pEntry));

               bResult = true;
            }
         }

         if (bResult)
         {
            // Listed before it is started, so a handshake that fails instantly
            // still finds a socket to report to.
            {
               std::lock_guard<std::mutex> guard (m_mxHub);

               m_apEntry.push_back (pEntry);
            }

            if (pEntry->pConn_Tls)
               m_ClientTls.connect (pEntry->pConn_Tls);
            else
               m_ClientPlain.connect (pEntry->pConn_Plain);
         }
      }

      return bResult;
   }

   bool Send (ISOCKET_LINK* pLink, const uint8_t* pData, size_t nSize, bool bBinary)
   {
      bool bResult = false;

      ENTRY_PTR pEntry = Entry_Find (pLink);

      if (pEntry)
      {
         std::lock_guard<std::mutex> guard (pEntry->mxEntry);

         if (!pEntry->bDetached)
         {
            websocketpp::frame::opcode::value eOpcode = bBinary ? websocketpp::frame::opcode::binary : websocketpp::frame::opcode::text;

            websocketpp::lib::error_code ec;

            if (pEntry->pConn_Tls)
               ec = pEntry->pConn_Tls->send (pData, nSize, eOpcode);
            else if (pEntry->pConn_Plain)
               ec = pEntry->pConn_Plain->send (pData, nSize, eOpcode);

            bResult = !ec;
         }
      }

      return bResult;
   }

   bool Close (ISOCKET_LINK* pLink, uint16_t wCode, const std::string& sReason)
   {
      bool bResult = false;

      ENTRY_PTR pEntry = Entry_Find (pLink);

      if (pEntry)
      {
         std::lock_guard<std::mutex> guard (pEntry->mxEntry);

         if (!pEntry->bDetached)
         {
            websocketpp::lib::error_code ec;

            if (pEntry->pConn_Tls)
               pEntry->pConn_Tls->close (wCode, sReason, ec);
            else if (pEntry->pConn_Plain)
               pEntry->pConn_Plain->close (wCode, sReason, ec);

            bResult = !ec;
         }
      }

      return bResult;
   }

   uint64_t Buffered (ISOCKET_LINK* pLink) const
   {
      uint64_t nResult = 0;

      ENTRY_PTR pEntry = Entry_Find (pLink);

      if (pEntry)
      {
         std::lock_guard<std::mutex> guard (pEntry->mxEntry);

         if (!pEntry->bDetached)
         {
            if (pEntry->pConn_Tls)
               nResult = static_cast<uint64_t> (pEntry->pConn_Tls->get_buffered_amount ());
            else if (pEntry->pConn_Plain)
               nResult = static_cast<uint64_t> (pEntry->pConn_Plain->get_buffered_amount ());
         }
      }

      return nResult;
   }

   void Detach (ISOCKET_LINK* pLink)
   {
      ENTRY_PTR pEntry;

      {
         std::lock_guard<std::mutex> guard (m_mxHub);

         for (size_t i = 0; i < m_apEntry.size ()  &&  !pEntry; i++)
         {
            if (m_apEntry[i]->pLink == pLink)
            {
               pEntry = m_apEntry[i];

               m_apEntry.erase (m_apEntry.begin () + i);
            }
         }
      }

      if (pEntry)
      {
         CLIENT_TLS::connection_ptr   pConn_Tls;
         CLIENT_PLAIN::connection_ptr pConn_Plain;

         {
            std::lock_guard<std::mutex> guard (pEntry->mxEntry);

            pEntry->bDetached = true;

            pConn_Tls   = pEntry->pConn_Tls;
            pConn_Plain = pEntry->pConn_Plain;
         }

         // Nothing reports anywhere any more, so the connection can be told to
         // go away and unwind on the io thread in its own time.
         websocketpp::lib::error_code ec;

         if (pConn_Tls)
            pConn_Tls->close (websocketpp::close::status::going_away, "", ec);
         else if (pConn_Plain)
            pConn_Plain->close (websocketpp::close::status::going_away, "", ec);
      }
   }

private:

   ENTRY_PTR Entry_Find (ISOCKET_LINK* pLink) const
   {
      ENTRY_PTR pResult;

      std::lock_guard<std::mutex> guard (m_mxHub);

      for (size_t i = 0; i < m_apEntry.size ()  &&  !pResult; i++)
      {
         if (m_apEntry[i]->pLink == pLink)
            pResult = m_apEntry[i];
      }

      return pResult;
   }

   // The subprotocol list is offered in the order it was written, which is the
   // order of preference the server is expected to honor.

   template <typename CONNECTION>
   void Subprotocol_Add (CONNECTION pConn, const std::string& sProtocol)
   {
      size_t nStart = 0;

      while (nStart <= sProtocol.size ()  &&  !sProtocol.empty ())
      {
         size_t      nComma = sProtocol.find (',', nStart);
         std::string sOne   = sProtocol.substr (nStart, (nComma == std::string::npos) ? std::string::npos : nComma - nStart);

         size_t nFirst = sOne.find_first_not_of (" \t");
         size_t nLast  = sOne.find_last_not_of  (" \t");

         if (nFirst != std::string::npos)
         {
            websocketpp::lib::error_code ec;

            pConn->add_subprotocol (sOne.substr (nFirst, nLast - nFirst + 1), ec);
         }

         nStart = (nComma == std::string::npos) ? sProtocol.size () + 1 : nComma + 1;
      }
   }

   // The four callbacks, installed per connection. Each one locks the weak
   // reference, then the entry, then reports - so a Detach racing it either wins
   // (and the callback finds bDetached) or waits (and the callback finishes
   // against a socket that is still there).

   template <typename CLIENT>
   void Handler_Set (CLIENT* pClient, typename CLIENT::connection_ptr pConn, std::weak_ptr<ENTRY> pwEntry)
   {
      pConn->set_open_handler ([pClient, pwEntry] (websocketpp::connection_hdl hdl)
      {
         std::string sProtocol;

         websocketpp::lib::error_code ec;

         typename CLIENT::connection_ptr pConn_Open = pClient->get_con_from_hdl (hdl, ec);

         if (pConn_Open)
            sProtocol = pConn_Open->get_subprotocol ();

         ENTRY_PTR pEntry = pwEntry.lock ();

         if (pEntry)
         {
            std::lock_guard<std::mutex> guard (pEntry->mxEntry);

            if (!pEntry->bDetached)
               pEntry->pLink->OnOpened (sProtocol);
         }
      });

      pConn->set_message_handler ([pwEntry] (websocketpp::connection_hdl, typename CLIENT::message_ptr pMessage)
      {
         ENTRY_PTR pEntry = pwEntry.lock ();

         if (pEntry  &&  pMessage)
         {
            const std::string& sPayload = pMessage->get_payload ();

            bool bBinary = (pMessage->get_opcode () == websocketpp::frame::opcode::binary);

            std::lock_guard<std::mutex> guard (pEntry->mxEntry);

            if (!pEntry->bDetached)
               pEntry->pLink->OnMessage (reinterpret_cast<const uint8_t*> (sPayload.data ()), sPayload.size (), bBinary);
         }
      });

      pConn->set_fail_handler ([pClient, pwEntry] (websocketpp::connection_hdl hdl)
      {
         std::string sError;

         websocketpp::lib::error_code ec;

         typename CLIENT::connection_ptr pConn_Fail = pClient->get_con_from_hdl (hdl, ec);

         if (pConn_Fail)
            sError = pConn_Fail->get_ec ().message ();

         if (sError.empty ())
            sError = "the connection failed";

         ENTRY_PTR pEntry = pwEntry.lock ();

         if (pEntry)
         {
            std::lock_guard<std::mutex> guard (pEntry->mxEntry);

            if (!pEntry->bDetached)
               pEntry->pLink->OnFailed (sError);
         }
      });

      pConn->set_close_handler ([pClient, pwEntry] (websocketpp::connection_hdl hdl)
      {
         // The remote close code starts life as 1006 (abnormal closure) and is
         // replaced only when a close frame actually arrives, so 1006 here means
         // the peer dropped the connection without completing the closing
         // handshake -- which is exactly what "not clean" means to a browser.
         // 1005 (no status) is a clean close whose frame simply carried no code.
         uint16_t wCode  = 1006;
         bool     bClean = false;

         websocketpp::lib::error_code ec;

         typename CLIENT::connection_ptr pConn_Close = pClient->get_con_from_hdl (hdl, ec);

         if (pConn_Close)
         {
            wCode  = static_cast<uint16_t> (pConn_Close->get_remote_close_code ());
            bClean = (wCode != websocketpp::close::status::abnormal_close);
         }

         ENTRY_PTR pEntry = pwEntry.lock ();

         if (pEntry)
         {
            std::lock_guard<std::mutex> guard (pEntry->mxEntry);

            if (!pEntry->bDetached)
               pEntry->pLink->OnClosed (wCode, bClean);
         }
      });
   }

   asio::io_context                                   m_ioContext;
   std::unique_ptr<asio::executor_work_guard<asio::io_context::executor_type>> m_pWork;
   std::thread                                        m_thIo;
   bool                                               m_bRunning;

   CLIENT_TLS                                         m_ClientTls;
   CLIENT_PLAIN                                       m_ClientPlain;

   mutable std::mutex                                 m_mxHub;
   std::vector<ENTRY_PTR>                             m_apEntry;
};

/***********************************************************************************************************************************
**  SOCKET_HUB
***********************************************************************************************************************************/

SOCKET_HUB::SOCKET_HUB () :
   m_pImpl (new Impl ())
{
}

SOCKET_HUB::~SOCKET_HUB ()
{
   delete m_pImpl;
}

bool     SOCKET_HUB::Initialize ()                                                                       { return m_pImpl->Initialize (); }
bool     SOCKET_HUB::Connect    (ISOCKET_LINK* pLink, const std::string& sUrl, const std::string& sProto) { return m_pImpl->Connect (pLink, sUrl, sProto); }
bool     SOCKET_HUB::Send       (ISOCKET_LINK* pLink, const uint8_t* pData, size_t nSize, bool bBinary)   { return m_pImpl->Send (pLink, pData, nSize, bBinary); }
bool     SOCKET_HUB::Close      (ISOCKET_LINK* pLink, uint16_t wCode, const std::string& sReason)        { return m_pImpl->Close (pLink, wCode, sReason); }
uint64_t SOCKET_HUB::Buffered   (ISOCKET_LINK* pLink) const                                              { return m_pImpl->Buffered (pLink); }
void     SOCKET_HUB::Detach     (ISOCKET_LINK* pLink)                                                    {        m_pImpl->Detach (pLink); }
void     SOCKET_HUB::Shutdown   ()                                                                       {        m_pImpl->Shutdown (); }

/***********************************************************************************************************************************
**  SOCKET Impl Class
***********************************************************************************************************************************/

class SOCKET::Impl : public ISOCKET_LINK
{
public:
   Impl (SOCKET* pSocket, SOCKET_HUB* pHub, CONTAINER* pContainer, uint32_t nSocketIx, const std::string& sUrl, const std::string& sProtocol) :
      ISOCKET_LINK        (),
      m_pSocket           (pSocket),
      m_pHub              (pHub),
      m_pContainer        (pContainer),
      m_nSocketIx         (nSocketIx),
      m_sUrl              (sUrl),
      m_sProtocol_Request (sProtocol),
      m_bState            (kSOCKET_STATE_CLOSED),
      m_pListener         (nullptr)
   {
   }

   ~Impl ()
   {
      // Detach first. It is the hub's guarantee that no callback is running and
      // none ever will again, which is what makes tearing down the rest safe.
      m_pHub->Detach (this);
   }

   bool Initialize (ISOCKET* pListener)
   {
      bool bResult = false;

      {
         std::lock_guard<std::mutex> guard (m_mxSocket);

         m_pListener = pListener;
         m_bState    = kSOCKET_STATE_CONNECTING;
      }

      bResult = m_pHub->Connect (this, m_sUrl, m_sProtocol_Request);

      if (!bResult)
      {
         std::lock_guard<std::mutex> guard (m_mxSocket);

         m_bState = kSOCKET_STATE_CLOSED;
         m_sError = "not a WebSocket URL, or the connection could not be created";
      }

      return bResult;
   }

   bool Send (const uint8_t* pData, size_t nSize, bool bBinary)
   {
      bool bResult = false;

      if (nSize <= kSOCKET_FRAME_MAX  &&  State () == kSOCKET_STATE_OPEN)
         bResult = m_pHub->Send (this, pData, nSize, bBinary);

      return bResult;
   }

   void Close (uint16_t wCode, const std::string& sReason)
   {
      bool bClose = false;

      {
         std::lock_guard<std::mutex> guard (m_mxSocket);

         if (m_bState == kSOCKET_STATE_CONNECTING  ||  m_bState == kSOCKET_STATE_OPEN)
         {
            m_bState = kSOCKET_STATE_CLOSING;
            bClose   = true;
         }
      }

      if (bClose)
         m_pHub->Close (this, wCode, Reason_Trim (sReason));
   }

   eSOCKET_STATE State () const
   {
      std::lock_guard<std::mutex> guard (m_mxSocket);

      return m_bState;
   }

   std::string Protocol () const
   {
      std::lock_guard<std::mutex> guard (m_mxSocket);

      return m_sProtocol;
   }

   std::string Error () const
   {
      std::lock_guard<std::mutex> guard (m_mxSocket);

      return m_sError;
   }

   ISOCKET* Listener () const
   {
      std::lock_guard<std::mutex> guard (m_mxSocket);

      return m_pListener;
   }

   // -----------------------------------------------------------------------
   // ISOCKET_LINK - all four arrive on the hub's io thread, with the hub's
   // entry lock held. m_mxSocket is released before the listener is called so
   // it stays a leaf: the listener is free to read back off the socket.
   // -----------------------------------------------------------------------

   void OnOpened (const std::string& sProtocol) override
   {
      ISOCKET* pListener = nullptr;

      {
         std::lock_guard<std::mutex> guard (m_mxSocket);

         m_bState    = kSOCKET_STATE_OPEN;
         m_sProtocol = sProtocol;
         pListener   = m_pListener;
      }

      if (pListener)
         pListener->OnSocketOpened (m_pSocket);
   }

   void OnMessage (const uint8_t* pData, size_t nSize, bool bBinary) override
   {
      ISOCKET* pListener = Listener ();

      if (pListener)
         pListener->OnSocketMessage (m_pSocket, pData, nSize, bBinary);
   }

   void OnFailed (const std::string& sError) override
   {
      ISOCKET* pListener = nullptr;

      {
         std::lock_guard<std::mutex> guard (m_mxSocket);

         m_bState  = kSOCKET_STATE_CLOSED;
         m_sError  = sError;
         pListener = m_pListener;
      }

      // The browser's shape: the error is reported, and then the socket closes
      // with 1006 (abnormal closure) because no closing handshake happened.
      if (pListener)
      {
         pListener->OnSocketFailed (m_pSocket);
         pListener->OnSocketClosed (m_pSocket, 1006, false);
      }
   }

   void OnClosed (uint16_t wCode, bool bClean) override
   {
      ISOCKET* pListener = nullptr;

      {
         std::lock_guard<std::mutex> guard (m_mxSocket);

         m_bState  = kSOCKET_STATE_CLOSED;
         pListener = m_pListener;
      }

      if (pListener)
         pListener->OnSocketClosed (m_pSocket, wCode, bClean);
   }

   SOCKET*                                            m_pSocket;
   SOCKET_HUB*                                        m_pHub;
   CONTAINER*                                         m_pContainer;
   uint32_t                                           m_nSocketIx;
   std::string                                        m_sUrl;
   std::string                                        m_sProtocol_Request;

   mutable std::mutex                                 m_mxSocket;
   eSOCKET_STATE                                      m_bState;
   std::string                                        m_sProtocol;
   std::string                                        m_sError;
   ISOCKET*                                           m_pListener;
};

/***********************************************************************************************************************************
**  SOCKET
***********************************************************************************************************************************/

SOCKET::SOCKET (SOCKET_HUB* pHub, CONTAINER* pContainer, uint32_t nSocketIx, const std::string& sUrl, const std::string& sProtocol) :
   m_pImpl (new Impl (this, pHub, pContainer, nSocketIx, sUrl, sProtocol))
{
}

SOCKET::~SOCKET ()
{
   delete m_pImpl;
}

bool SOCKET::Initialize (ISOCKET* pListener) { return m_pImpl->Initialize (pListener); }

bool SOCKET::Send_Text   (const std::string& sText)              { return m_pImpl->Send (reinterpret_cast<const uint8_t*> (sText.data ()), sText.size (), false); }
bool SOCKET::Send_Binary (const uint8_t* pData, size_t nSize)    { return m_pImpl->Send (pData, nSize, true); }

void SOCKET::Close (uint16_t wCode, const std::string& sReason) { m_pImpl->Close (wCode, sReason); }

eSOCKET_STATE      SOCKET::State    () const { return m_pImpl->State (); }
uint64_t           SOCKET::Buffered () const { return m_pImpl->m_pHub->Buffered (m_pImpl); }
const std::string& SOCKET::Url      () const { return m_pImpl->m_sUrl; }
std::string        SOCKET::Protocol () const { return m_pImpl->Protocol (); }
std::string        SOCKET::Error    () const { return m_pImpl->Error (); }

uint32_t           SOCKET::SocketIx  () const { return m_pImpl->m_nSocketIx; }
CONTAINER*         SOCKET::Container () const { return m_pImpl->m_pContainer; }
ISOCKET*           SOCKET::Listener  () const { return m_pImpl->Listener (); }

std::string        SOCKET::ContainerName () const { return m_pImpl->m_pContainer->Identity ()->DisplayName (); }
