// Copyright 2026 Metaversal Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Build the wasm executable (run from this crate's directory):
//    cargo build --target wasm32-unknown-unknown --release --target-dir target
// Output: target/wasm32-unknown-unknown/release/panel.wasm
// Always pass --target-dir target; otherwise a CARGO_TARGET_DIR set in the shell
// can redirect the output elsewhere.

#![allow(non_snake_case, non_camel_case_types, dead_code)]

// ---------------------------------------------------------------------------
// Panel module
//
// Builds a single in-scene UI panel: an RmlUi RML+CSS document the host
// rasterizes to a textured quad and the compositor anchors over the 3D scene.
// The document is not embedded here - it is authored in the fabric's "Data"
// block at PANEL_PATH; this module reads it by path and hands it to the panel
// node. Any fabric that uses panel.wasm must place the document string there.
//
// It talks to the engine entirely through the sneeze SDK - the single-Call
// ABI - importing only Sneeze.Call and exporting the lifecycle plus the
// Alloc/Free/Notify memory hooks (all generated by sneeze::instance!).
// ---------------------------------------------------------------------------

use sneeze::*;

// Where this module reads the panel's RML+CSS document inside the "Data" block,
// as a dot-separated path. This is a contract with the fabric: the document
// string must live at "Data.sPanel".
const PANEL_PATH: &str = "sPanel";

// Celestial STARSYSTEM type - the root frame produces no geometry of its own;
// it only parents the panel.
const CELESTIAL_STARSYSTEM: u8 = 9;

struct PANEL;

impl INSTANCE for PANEL
{
   fn Init ()
   {
      // no per-module setup
   }

   fn Open (pFabric: FABRIC)
   {
      let pConsole = pFabric.Console ();

      pConsole.Log (&format! ("Panel WASM: Open (twFabricIx={})", pFabric.Index ()));

      // Root frame (STARSYSTEM): the fabric's root node, no geometry of its own.
      let mut pRootObject = SNEEZE_ABI_MAPOBJECT::Celestial ();
      pRootObject.Type (CELESTIAL_STARSYSTEM).Name ("Panel");

      let pRoot = pFabric.Scene ().Node_Root (&pRootObject);

      if pRoot.IsValid ()
      {
         // The in-scene panel, at the world origin so the default camera frames
         // it dead-center (with no other geometry the scene render-scale is 1.0).
         // Bound carries the quad's aspect ratio (1.6:1); the host rasterizes the
         // document and the compositor sizes the quad.
         let mut pPanelObject = SNEEZE_ABI_MAPOBJECT::Panel ();
         pPanelObject.Parent (pRoot.Class (), pRoot.ObjectIx ())
                     .Name   ("Panel")
                     .Bound  (1.6, 1.0, 0.0);

         let pPanel = pFabric.Scene ().Node_Open (&pPanelObject);

         if pPanel.IsValid ()
         {
            match pFabric.Data ().Get (PANEL_PATH)
            {
               Some (sRml) =>
               {
                  pPanel.Panel (&sRml);
                  pConsole.Log ("  Panel created");
               }
               None =>
               {
                  pConsole.Warn (&format! ("  No panel document at Data.{}", PANEL_PATH));
               }
            }
         }
         else
         {
            pConsole.Error ("  ERROR: Failed to create panel node");
         }
      }
      else
      {
         pConsole.Error ("  ERROR: Failed to create root node");
      }
   }

   fn Close (pFabric: FABRIC)
   {
      pFabric.Console ().Log ("Panel WASM: Close");
   }

   fn Shutdown ()
   {
      // no per-module teardown
   }
}

sneeze::instance! (PANEL);
