// Copyright 2026 Metaversal Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Build the wasm executable (run from this crate's directory):
//    cargo build --target wasm32-unknown-unknown --release --target-dir target
// Output: target/wasm32-unknown-unknown/release/map.wasm
// Always pass --target-dir target; otherwise a CARGO_TARGET_DIR set in the shell
// can redirect the output elsewhere.

#![allow(non_snake_case, non_camel_case_types, dead_code)]

// ---------------------------------------------------------------------------
// Generic map module
//
// This module owns no scene data. On Open it hands the fabric over to the
// browser's map-managed path: a single call to SCENE::Node_Map injects the
// node tree the MSF "Data" block carries at the SCENE_PATH path. The rest of
// "Data" is free for other uses. This stands in for a real map service until
// network connectivity to one is built in.
//
// It talks to the engine entirely through the sneeze SDK - the single-Call
// ABI - so it imports only Sneeze.Call and exports the lifecycle plus the
// Alloc/Free/Notify memory hooks (all generated by sneeze::instance!).
// ---------------------------------------------------------------------------

use sneeze::*;

// Where this module expects the scene tree to live inside the MSF "Data"
// block, as a dot-separated path. This is a hardcoded contract: any fabric
// that uses map.wasm must place its node tree at "Data.Scene". An empty string
// here would instead read the whole "Data" block as the tree.
const SCENE_PATH: &str = "Scene";

struct MAP;

impl INSTANCE for MAP
{
   fn Open (pFabric: FABRIC)
   {
      let pConsole = pFabric.Console ();

      pConsole.Log (&format! ("Map WASM: Open (twFabricIx={})", pFabric.Index ()));

      let pNode = pFabric.Scene ().Node_Map (SCENE_PATH);

      if pNode.IsValid ()
      {
         pConsole.Log (&format! ("  Map loaded: root={}", pNode.Composed ()));
      }
      else
      {
         pConsole.Error ("  ERROR: Node_Map failed");
      }
   }

   fn Close (pFabric: FABRIC)
   {
      pFabric.Console ().Log ("Map WASM: Close");
   }
}

sneeze::instance! (MAP);
